<a href="https://colab.research.google.com/github/2303A52486/FMML_Projects_Assignments_2024/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Basics of Linear Algebra**

Importing the NumPy library for Linear Algebra functions and Matplotlib for some plotting functions.

In [3]:
import numpy as np
import matplotlib.pyplot as plt

## Transpose of Matrix

Matrix transpose is performed with the transpose method on a nested list or a Python array, or a higher-dimensional Numpy array.

In [10]:
# Tanspose of a Matrix
a = [[9,8,6],[5,7,4],[3,2,0]]
b = np.transpose(a)
print('a:\n',a)
print('b:\n',b)

a:
 [[9, 8, 6], [5, 7, 4], [3, 2, 0]]
b:
 [[9 5 3]
 [8 7 2]
 [6 4 0]]


If the matrix is a NumPy array, it can be treated as an object and method T can be applied over it as follows.

In [9]:
# Transpose of a Matrix(as NumPy array)
print("Matrix and its Transpose")
a = np.array([[9,8,6,5],[7,3,2,1]])
b = a.T
print('a:\n',a)
print('b:\n',b)

Matrix and its Transpose
a:
 [[9 8 6 5]
 [7 3 2 1]]
b:
 [[9 7]
 [8 3]
 [6 2]
 [5 1]]


The dot method of NumPy performs dot-matrix product (scalar product) for 1D or higher dimensional arrays. If the inputs are scalars (numbers), it performs multiplication.

In [11]:
# Scalars

a = 4
b = 9
c = np.dot(a,b)
print(c)

36


In the case of one- or higher-dimensional arrays, the inputs can be either NumPy arrays, Python arrays, Python lists or Python’s nested lists.

In [14]:
# 1D arrays or vectors
a = np.array([9,8,6])  # or a = [9,8,6]
b = np.array([5,7,1])  # or b = [5,7,1]
c = np.dot(a,b)
print(c)

107


In [3]:
# 2D arrays or matrices
# 2D arrays or matrices
a = [[9,8,6],[5,7,4],[3,2,0]]
b = [[3,-1,5],[-2,-6,4], [0,4,4]]
z = np.dot(a,b)
print(z)

[[ 11 -33 101]
 [  1 -31  69]
 [  5 -15  23]]


We can obtained the same result using np.matmul().

In [4]:
c = np.matmul(a,b)
print(c)

[[ 11 -33 101]
 [  1 -31  69]
 [  5 -15  23]]


**Numpy Arrays**
A NumPy array is a Numpy object upon which the dot method can be performed as below. However, this method accepts only NumPy arrays to operate on.

In [6]:
# convert lists into NumPy arrays
newa = np.array(a)
newb = np.array(b)
c = newa.dot(newb)
print(c)

[[ 11 -33 101]
 [  1 -31  69]
 [  5 -15  23]]


### The multi_dot method
It performs dot (scalar) product with 2 or more input matrices. First and last arrays can be either 1D or 2D arrays. However, the dimensions of the matrices must suit subsequent scalar matrix multiplication.

In [4]:
# matrices with random integers: entries ranging from -4 to 4
a = np.random.randint(-4,4,(500,5))
b = np.random.randint(-4,4,(5,1000))
c = np.random.randint(-4,4,(1000,10))
d = np.random.randint(-4,4,(10,2000))
e = np.random.randint(-4,4,(2000,200))

# Perform multiple matrix multiplication
z = np.linalg.multi_dot([a,b,c,d,e])

The result of this method can be obtained with successive dot products of matrices but multi_dot functions in an optimized manner. It decides the order of dot multiplication to complete the entire process efficiently.

In [5]:
%%time
z = np.linalg.multi_dot([a,b,c,d,e])
print(z, '\n')

[[-17073684 -12364142 -13967321 ... -13646039 -15952211 -14164224]
 [ -6796644  -4030712  -5154404 ...  -4124664  -6431000  -5760580]
 [ -7551984  -5186536  -6066545 ...  -5729169  -6985830  -7567756]
 ...
 [-15530532 -10194126 -11373424 ... -11341748 -15015911 -12220573]
 [-23299056 -16629074 -18702219 ... -19614904 -21765483 -19178362]
 [  -883172   -594764    136750 ...     67612  -1376466    176518]] 

CPU times: user 16 ms, sys: 0 ns, total: 16 ms
Wall time: 18.6 ms


In [6]:
%%time
z = a.dot(b).dot(c).dot(d).dot(e)
print(z, '\n')

[[-17073684 -12364142 -13967321 ... -13646039 -15952211 -14164224]
 [ -6796644  -4030712  -5154404 ...  -4124664  -6431000  -5760580]
 [ -7551984  -5186536  -6066545 ...  -5729169  -6985830  -7567756]
 ...
 [-15530532 -10194126 -11373424 ... -11341748 -15015911 -12220573]
 [-23299056 -16629074 -18702219 ... -19614904 -21765483 -19178362]
 [  -883172   -594764    136750 ...     67612  -1376466    176518]] 

CPU times: user 482 ms, sys: 12.3 ms, total: 494 ms
Wall time: 541 ms


### Inner Product

The inner product is the scalar multiplication of one vector (or matrix) and the transpose of another vector (or matrix). If both arrays are 1D arrays, their dimensions should be identical. If either or both arrays are higher-dimensional, then the last dimensions of both arrays should be identical.

In [42]:
a = np.array([[5,7,4],[3,2,0]])
b = np.array([6,3,2])
c = np.inner(b,a)
print(c)

[59 24]


In [8]:
# The same results can be obtained using the dot method as follows.

a.dot(b.T)

array([18, 21])

### Outer Product
Outer product is the dot product of a column vector of size Mx1 and a row vector of size 1xN. The resulting array is a matrix of size MxN.

In [37]:
a = np.array([6,4,5,2,10])
b = np.array([23,12,4])
c = np.outer(a,b)
print(c)

[[138  72  24]
 [ 92  48  16]
 [115  60  20]
 [ 46  24   8]
 [230 120  40]]


The last dimension of the second array and the second-to-last dimension of the first array should be identical to perform matrix multiplication. Further, the symbol @ is also used to perform matrix multiplication.

In [35]:
# Here, 'a' matrix is 3D, which means there are 3 matrices each of 2x5 size
# Similarly, for 'b' matrix
# So we perform 3 matrix multiplication operations each with 2x5 and 5x3 matrices from a and b
a = np.random.random([3,2,5])
b = np.random.random([3,5,3])
c = a @ b
print(c.shape)

(3, 2, 3)


### Matrix Determinant

Matrix determinant can be calculated using the method det available in the linalg module.

In [29]:
# generate a random integer matrix of size 3 by 3
a = np.random.randint(10,26,[3,3])
det = np.linalg.det(a)
print(int(det))

-2191


### Matrix Inverse

Inverse of a square matrix can be derived using the inv method of the linalg module.

In [27]:
a = np.random.randint(1,8,[3,3])
inv = np.linalg.inv(a)
print(a)
print()
print(inv)


[[4 7 1]
 [5 5 1]
 [1 6 2]]

[[-0.18181818  0.36363636 -0.09090909]
 [ 0.40909091 -0.31818182 -0.04545455]
 [-1.13636364  0.77272727  0.68181818]]


### Matrix Power

Matrix Power is a general method to obtain either positive or negative powers of a given square matrix. The first negative power of a matrix is technically termed its inverse. Thus, the matrix_power method can be used to find the inverse or any power of a matrix.

In [13]:
a = np.random.random([3,3])

# positive powers of matrix
a_3 = np.linalg.matrix_power(a, 3)
a_6 = np.linalg.matrix_power(a, 6)

# inverse of matrix
a_inv_2 = np.linalg.matrix_power(a, -2)
a_inv_4 = np.linalg.matrix_power(a, -4)

print('matrix \n', a)
print('\n matrix to the power 2\n', a_3)
print('\n matrix to the power 7\n', a_6)
print('\n matrix inverse \n', a_inv_2)
print('\n matrix cubic inverse \n', a_inv_4)

matrix 
 [[0.44472801 0.48281347 0.02398902]
 [0.37007619 0.6671838  0.14816889]
 [0.37617678 0.69839708 0.1441801 ]]

 matrix to the power 2
 [[0.40853533 0.61529852 0.10362491]
 [0.52550705 0.80098348 0.13758371]
 [0.54052791 0.82407724 0.14160417]]

 matrix to the power 7
 [[0.54625699 0.82961007 0.14166321]
 [0.7099785  1.07829785 0.18414033]
 [0.73042416 1.10935106 0.1894435 ]]

 matrix inverse 
 [[   93.7760542  -2651.21193461  2507.48281559]
 [  -85.57571664  2808.29345457 -2664.88961583]
 [  142.71190795 -6218.02472638  5938.06362147]]

 matrix cubic inverse 
 [[   593520.96638406 -23285591.46501053  22189921.48701081]
 [  -628658.1595136   24683741.01254402 -23522655.78716331]
 [  1392927.27063192 -54763424.07812699  52188796.75365701]]


### Eigenvalues and Eigenvectors

Eigenvalues and Eigenvectors of a matrix can be determined as follows. If Eigen values cannot be determined, the method throws an error (Eg. Singular matrix).

In [19]:
a = np.arange(9).reshape(3,3)
eig_val, eig_vec = np.linalg.eig(a)
print('Eigenvalues are: \n', eig_val)
print('\nEigenvectors are: \n', eig_vec)

Eigenvalues are: 
 [ 1.33484692e+01 -1.34846923e+00 -2.48477279e-16]

Eigenvectors are: 
 [[ 0.16476382  0.79969966  0.40824829]
 [ 0.50577448  0.10420579 -0.81649658]
 [ 0.84678513 -0.59128809  0.40824829]]


In [20]:
# Eigenvalues alone can be determined using the method eigvals as shown below.

a = np.arange(9).reshape(3,3)
eigenvalues = np.linalg.eigvals(a)
print(eigenvalues)

[ 1.33484692e+01 -1.34846923e+00 -2.48477279e-16]


### Traces of a Matrix

Traces of a square matrix is the summation of its diagonal elements.

In [21]:
a = np.eye(4)
print(a)
c = np.trace(a)
print('\nTrace of matrix is: ',c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Trace of matrix is:  4.0


### Matrix Norm

Matrix or vector norm is calculated using the norm method of the linalg module.

In [22]:
a = np.arange(16).reshape(4,4)
n = np.linalg.norm(a)
print(a)
print('\n Frobenius Norm of above matrix:')
print(n)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 Frobenius Norm of above matrix:
35.21363372331802


### Norm of Matrix

Axis-wise norm determination is also possible by specifying the axis as an integer.

In [24]:
# Norm along axis 0
a = np.arange(6).reshape(3,2)
z = np.linalg.norm(a, axis=0)
print(z)

[4.47213595 5.91607978]


### Solving System of Equations

When we think of Linear Algebra, the system of linear equations comes to our mind first, as it is tedious, time-consuming and error-prone. NumPy solves systems of linear equations in a fraction of seconds!

In [25]:
# Coefficient Matrix
a = np.random.randint(5,25,[4,4])

# Dependent variable vector
b = np.array([2,3,7,9.2])

# solution
x = np.linalg.solve(a,b)
print('Coefficient Matrix')
print(a)
print('\nDependent Variable vector')
print(b)
print('\nSolution')
print(x)

Coefficient Matrix
[[20  6 23 11]
 [ 5 22 17 15]
 [20 20  6 21]
 [15 14  5  6]]

Dependent Variable vector
[2.  3.  7.  9.2]

Solution
[ 0.3970235   0.48909922 -0.16409922 -0.46370757]


### Singular Value Decomposition

Singular Value Decomposition (SVD) is one of the great dimension-reduction algorithms in machine learning. It identifies the principal components and arranges them by rank. The top ranked components contribute greatly to the original array. Here, we explore SVD with an image to get better understanding.